### ISSUE TITLE
color-mod-function does not transform vars

### ISSUE THREAD

**Issue by steverandy** [csstools/postcss-preset-env#79]
Upgraded to v6.0.3 and got the following error: 

```
(246:5) Expected a color

  244 |     text-align: center;
  245 |     display: inline-block;
> 246 |     background: color-mod(var(--purple-color) alpha(24%));
```

My config:

```
"postcss-preset-env": {
  stage: 0,
  features: {
    "color-mod-function": true
  },
  autoprefixer: {remove: false}
}
```

```
"browserslist": "electron >= 2.0.0"
```

**Comment by martinmethod** [comment]
@steverandy, probably you need to pass the CSS file that contains the variables by using `importFrom` property like so:

```
'postcss-preset-env': {
  stage: 0,
  features: {
    'color-mod-function': {
        importFrom: ['relative/path/to/file.css']
      }
  }
}
```

**HOWEVER...**

There is something wrong with **color-mod** using CSS custom property when it's called inside nested declaration with **&**.

So, for example I have the following code...

```
.root {
  background-color: color-mod(var(--swatch-col-yellow) a(80%)); // this one passes

  &[data-current] {
    background-color: color-mod(var(--swatch-col-yellow) a(60%)); // this one fails
  }
}
```

... where the first `color-mod` (directly in `.root`) is parsed perfectly, while the second one fails with `Expected a color` and they both rely on same variable.

I successfully import my CSS files that contains all my variables, just as you told me yesterday, like so:

```
  require('postcss-preset-env')({
    stage: 0,
    importFrom: cssVariables,
    features: {
      'color-mod-function': {
        importFrom: cssVariables
      }
    }
  })
```

Everything works properly, just except **color-mod** with CSS variable inside nested `& { ... }` declaration.

You may test it here: [https://github.com/martinmethod/testapp](https://github.com/martinmethod/testapp).

**Comment by steverandy** [comment]
@martinmethod I have tried `importFrom` option but still getting the same error.

Currently I'm using `postcss-import` to import the variables.

```
module.exports = {
  plugins: {
    "postcss-import": {path: srcPath},
    "postcss-mixins": {},
    "postcss-preset-env": {
      stage: 0,
      features: {
        "color-mod-function": true
      },
      autoprefixer: {remove: false}
    }
  }
};
```

The color-mod works perfectly on v5.3.0.

**Comment by jonathantneal** [comment]
This issue is hard to track, as two of you seem to be discussing two different things.

Please create a small repo that demonstrates your problem. I don’t yet see something I can reproduce.

**Comment by martinmethod** [comment]
> This issue is hard to track, as two of you seem to be discussing two different things.
> 
> Please create a small repo that demonstrates your problem. I don’t yet see something I can reproduce.

Well, it turned out it actually has to do something with the `importFrom` property I guess. I pass several css files containing CSS variables with `importFrom` and the order of those files.

You can test that out here [https://github.com/martinmethod/testapp](https://github.com/martinmethod/testapp). Make sure you have the latest commits from `master` and do a `yarn install` before `yarn serve:dev`. So here's what you need to know:

There are several CSS files that are passed through `importFrom` and they all contain only CSS variable declarations. Let's focus on the first two files:
– swatches_colors.css
– swatches_offsets.css

I both pass them in the same exact order (swatches_offsets.css second).
There is this variable called `--swatch-col-test` and it isdefined in `swatches_offsets.css` file. And the compiler doesn't get that variable obviously, as the system returns error `"Expected a color"`. However, if I stop the server, move this variable to the first css file `swatches_colors.css` and run the server again, then it's working. So, it feels like that except for the first given file in the `importFrom` array every next one is ignored or not parsed properly.

**Comment by jonathantneal** [comment]
Ah, this was the same bug in PostCSS Custom Properties.

I have resolved the bug in PostCSS Color-Mod() Function 3.0.2 which has been bumped in PostCSS Preset Env 6.0.4.

**Comment by martinmethod** [comment]
> Ah, this was the same bug in PostCSS Custom Properties.
> 
> I have resolved the bug in PostCSS Color-Mod() Function 3.0.2 which has been bumped in PostCSS Preset Env 6.0.4.

All perfect now. Thanks! :)

Btw (if you see this), does it has a chance for `importFrom` to start taking `.scss` files as well?

**Comment by steverandy** [comment]
I've created a small demo to show the issue: https://github.com/steverandy/postcss-demo

If you run `npm run postcss src/main.css` you should get the following error:

```
CssSyntaxError: postcss-preset-env: /Git/postcss-demo/src/main.css:8:5: Expected a color

   6 |     font-weight: 600;
   7 |     width: 14px;
>  8 |     background: color-mod(var(--purple-color) alpha(24%));
     |     ^
   9 |   }
  10 | }
```

The error is gone if you do:
- Remove `"browserslist": "electron >= 2.0.0"` in package.json
- Set preserve to false `"custom-properties": {preserve: false}`

**Comment by jonathantneal** [comment]
@martinmethod, yes, you can specify the type of alternative files.

```js
{
  importFrom: [{
    "from" "path/to/file.scss",
    "type": "css"
  }]
}
```

However, these files will be parsed as CSS, so this may not work if the SCSS syntax somehow breaks the parser.

**Comment by jonathantneal** [comment]
@steverandy, thank you for making a repo to demonstrate this issue. I will look into it right now.

**Comment by steverandy** [comment]
@jonathantneal Just pushed an update. Can you please try again? Thanks.

**Comment by jonathantneal** [comment]
@steverandy, yes the issue is with color-mod when used with variables and hsl.

**Comment by jonathantneal** [comment]
@steverandy, I changed the test to just this:

```pcss
:root {
  --rgb: #b366ff;
  --hsl: hsl(270, 100%, 70%);
}

test {
  --test-rgb: color-mod(#b366ff alpha(25%));
  --test-hsl: color-mod(hsl(270, 100%, 70%) alpha(25%));
  --test-rgb-var: color-mod(var(--rgb) alpha(25%));
  --test-hsl-var: color-mod(var(--hsl) alpha(25%));
}
```

And the result is:

```pcss
:root {
  --rgb: #b366ff;
  --hsl: hsl(270, 100%, 70%);
}

test {
  --test-rgb: rgba(179, 102, 255, 0.25);
  --test-hsl: hsla(270, 100%, 70%, 0.25);
  --test-rgb-var: rgba(179, 102, 255, 0.25);
  --test-hsl-var: color-mod(hsl(270, 100%, 70%) alpha(25%));
}
```

Since `color-mod()` is a rejected standard, could you reduce your test (perhaps to the code I provided) and open it there?

https://github.com/jonathantneal/postcss-color-mod-function/issues/new

**Comment by steverandy** [comment]
Will open a new issue there.
I did not have this issue before upgrading to v6.
Is this issue related to PostCSS v7 upgrade?

**Comment by jonathantneal** [comment]
That I’m not sure of.

**Comment by steverandy** [comment]
Is there an alternative way to programmatically adding alpha value to hsl without using the color-mod plugin?

**Comment by jonathantneal** [comment]
There is no reasonable way to modify colors in CSS at all. FWIW, `color-mod()` was not rejected because there is not a need; it was rejected because they determined the syntax was wrong.

**Comment by jonathantneal** [comment]
FWIW, this has been fixed in postcss-color-mod-function 3.0.3. That update has been pushed into postcss-preset-env 6.0.5.

**Comment by steverandy** [comment]
Thank you for pushing the fix so quickly!

**Comment by evilebottnawi** [comment]
@jonathantneal looks problem still exists

```css
a {
  color-mod(var(--brandColorComplement) l(- 5%))
}
```

throw `ParserError`, you can reproduce this here https://preset-env.cssdb.org/playground

**Comment by jfroffice** [comment]
any update on this issue @jonathantneal
