### ISSUE TITLE
Custom selectors breaking

### ISSUE THREAD

**Issue by iamso** [csstools/postcss-preset-env#89]
Hi

after reading that cssNext has been deprecated and that I should use postcss-preset-env instead, I have done just that. At least I have updated my project template to use the new plugin.

I have then tested it on a personal project I had been working on and it broke my css. Mainly it broke my custom selectors. After trying to find the error, I've found that it works in very few cases, but doesn't in most.

Here is some sample code:
```postcss
@custom-selector :--nav-open-header .site-loaded .nav-toggle-input:checked ~ .site-header &;
@custom-selector :--nav-open-header-no-touch .site-loaded.no-touchevents .nav-toggle-input:checked ~ .site-header &;

/* first one works, second one breaks */
:--nav-open-header ul,
:--nav-open-header-no-touch:hover ul {
  background: red;
}

/* both break */
ul {
  :--nav-open-header,
  :--nav-open-header-no-touch:hover {
    background: red;
  }  
}

/* this one breaks too */
ul {
  &,
  :--nav-open-header {
    background: red;
  }
}

/* this one doesn't break */
ul {
  :--nav-open-header,
  & {
    background: red;
  }
}

/* here the second one breaks again */
ul {
  :--nav-open-header,
  :--nav-open-header-no-touch:hover,
  & {
    background: red;
  }
}
```

I have tested this code here https://preset-env.cssdb.org/playground and it behaves exactly as in my local setup.

Don't worry about the nesting, I use another postcss plugin to take care of that. But most of that code would break with or without nesting. I have tested that too.

Please let me know, if I can do anything more to help.

Thanks
Steve

**Comment by jonathantneal** [comment]
It looks like you were using some invalid queries. You may have been using an older version of cssnext that did not respect the web standard.

```
ul {
  :--nav-open-header
```

That is not possible.

**Comment by iamso** [comment]
@jonathantneal this is totally irrelevant. As mentioned before, the nesting is handled by another postcss plugin.

To illustrate, go ahead to https://preset-env.cssdb.org/playground and try the following code (with no nesting this time 😉):
```postcss
@custom-selector :--nav-open-header .site-loaded .nav-toggle-input:checked ~ .site-header;
@custom-selector :--nav-open-header-no-touch .site-loaded.no-touchevents .nav-toggle-input:checked ~ .site-header;

:--nav-open-header ul,
:--nav-open-header-no-touch:hover ul {
  background: red;
}
```

The expected output is this:
```css
.site-loaded .nav-toggle-input:checked~.site-header ul,
.site-loaded .no-touchevents .nav-toggle-input:checked~.site-header:hover ul {
  background: red;
}
```

But what you get instead is this:
```css
.site-loaded .nav-toggle-input:checked~.site-header ul,
.site-loaded
.no-touchevents 
.nav-toggle-input
:checked
~
.site-header:hover ul {
  background: red;
}
```

As you can see, it breaks the `:checked` part of the selector and therefore it doesn't work.

It does work if you only use one, but with two, like in this example, it breaks the second one.

**Comment by jonathantneal** [comment]
> the nesting is handled by another postcss plugin.

> go ahead to preset-env.cssdb.org/playground and try the following code

I can’t. It doesn’t have the other postcss plugin.

**Comment by jonathantneal** [comment]
When you have time, please create a small repo that replicates the issue. I can use that to determine if the code should be working and if there is a problem with one of the plugins.

See https://github.com/csstools/postcss-preset-env/blob/master/CONTRIBUTING.md#reporting-issues for more details.

**Comment by iamso** [comment]
@jonathantneal the code I have just posted doesn't need that plugin, that's why I wrote:
> (with no nesting this time 😉)

Just look at the code, the expected result and the actual result.
And if you want to see it for yourself, just copy the code, paste into the editor of the link and look at the result.

**Comment by jonathantneal** [comment]
Okay, I can verify the issue. The following CSS does work:

```pcss
@custom-selector :--foobar .foo.bar;

:--foobar, a {
  background: red;
}
```

While the following CSS does not work:

```pcss
@custom-selector :--foobar .foo.bar;

a, :--foobar {
  background: red;
}
```

It instead becomes:

```pcss
a, .foo .bar {
  background: red;
}
```

This may be an issue with [postcss-selector-parser](https://github.com/postcss/postcss-selector-parser).

**Comment by jonathantneal** [comment]
@iamso, I would recommend not using custom selectors until we have someone who can take on the bug, continuing the discussion in https://github.com/postcss/postcss-selector-parser/issues/157. Updating my comments there.

**Comment by jonathantneal** [comment]
Since October, we have made many releases and perhaps this is resolved. If not, this issue can be re-opened.

**Comment by iamso** [comment]
@jonathantneal I have just tried it with the latest version of postcss-preset-env (6.5.0) and the issue still exists.

**Comment by iamso** [comment]
@jonathantneal the issue is still not resolved
